services:
  - type: web
    name: accounting-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: accounting-app
          property: port
      - key: MONGO_URI
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
